### ISSUE TITLE
Error loading custom_components.sensor.sense. Make sure all dependencies are installed

### ISSUE THREAD

**Issue by JesseWebDotCom** [kbickar/sense-hass#1]
I'm trying to test this on a Mac and get the following error:

```
ERROR:homeassistant.loader:Error loading custom_components.sensor.sense. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jessetorres/.homeassistant/custom_components/sensor/sense.py", line 18, in <module>
    from sense_api import Senseable
ModuleNotFoundError: No module named 'sense_api'
ERROR:homeassistant.loader:Unable to find component sensor.sense
```

**Comment by kbickar** [comment]
The component can be found in the official home assistant repo:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/sensor/sense.py

Should be 0.65

If you're manually installing it, you may need to install the api lib with:
pip install sense_energy

**Comment by JesseWebDotCom** [comment]
OK, I guess I'll have to wait for 0.65 to officially release

**Comment by JesseWebDotCom** [comment]
Actually I got it working by adding the file you link to my custom_components\sensor directory and updating my configuration as documented here:
https://github.com/home-assistant/home-assistant.github.io/blob/d931145e3ea75a6b3ae5212be8ed1017582def01/source/_components/sensor.sense.markdown

Thanks for this.  I'd love to see sense discovered devices exposed as sensors in home assistant.  Is that something you're looking to do?
